name: Deploy REGIX Bot to Local Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build and Restart Bot Locally
        run: |
          source $HOME/.bashrc
          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"

          bun install
          bunx prisma db push
          bunx prisma generate

          pm2 restart regix-bot --update-env || pm2 start bun --name "regix-bot" -- src/bot.ts
